### PR TITLE
Add --no-perms option to skip setting permissions

### LINKED ISSUE #9: Add an option to skip setting the file permissions
In some cases it's desirable to skip setting the destination file permissions, it would be nice if `xcp` had an option for that.

### PR DESCRIPTION
**Pull request by lnicola**
Fixes #9.

### CODE REVIEW

**Comment by tarka** [comment]
Hi,

Thanks for the PR. I'm happy to merge this feature, but it can be improved a bit first. I'm not keen on using bare `bool`s as flags here, as we'll probably be adding more flags for similar options (e.g. xattrs). It would be better to pass the Opts down to the low-level functions and let them access the flags as needed.

To help with this I've made some modifications to support passing Opts about, including moving to scoped threads (which I've been procrastinating for a bit anyway). I've also modified `copy_file` to give it access to the Opts structure,so this can be used there now. Can I ask you to update you PR with the following:
* Use Opts to decide whether to copy permissions rather than passing a bool.
* Also update the parblock driver with the permissions changes.
* Add a test for your new flag.

Thanks,
Steve

**Comment by lnicola** [comment]
Sure, sorry for taking the easy way out there. I rebased the PR and updated it with your suggestions (not sure why I missed the `set_permissions` call in `parblock` the first time). There are some slight formatting differences in the diff, if you find it unreadable I can split them to a different commit.

**Comment by tarka** [comment]
Awesome, thanks.

**Comment by tarka** [comment]
BTW, I'll probably release this at the weekend.

**Pull request merged**
